### PR TITLE
ci: add .github/workflows/workflow.yml

### PR DESCRIPTION
**Pull request by abetomo**
#203: I couldn't re-open it after a force push, so I opened a new PR.

### CODE REVIEW

**Comment by abetomo** [comment]
This is the result of my repository.
https://github.com/abetomo/aws-sdk-mock/actions/runs/938903291

I think GitHub Action will work once it is merged into this repository.

**Review by nelsonic — APPROVED** [review]
@abetomo looks great. Thanks very much for making the time to add this. 🚀

**Comment by abetomo** [comment]
https://github.com/dwyl/aws-sdk-mock/actions/runs/940674928
GitHub Actions worked.

**Comment by nelsonic** [comment]
Nice one @abetomo 🚀

**Pull request merged**
