### PR TITLE
Upgrade to sinon 4.5.0

### PR DESCRIPTION
**Pull request by chris-armstrong**
This pull requests upgrades to a much newer version of sinon (4.5.0) which enables a much broader spy assertion API than v1

### CODE REVIEW

**Comment by chris-armstrong** [comment]
Note that this fails the Node v0.10.36 Travis CI, but this version of Node is passed its LTS maintenance End-Of-Life (https://github.com/nodejs/Release). It passes the v4 build just fine

**Comment by nelsonic** [comment]
@chris-armstrong yeah, the only reason we had Node.js `v.0.10.36` was for "legacy" AWS Lambda support. but given that Lambda has _discontinued_ support for any version prior to `v4.3.2` so I'm _happy_ to _substitute_ `- 0.10.36` for  ``"- node"` in `.travis.yml` 

https://travis-ci.org/dwyl/aws-sdk-mock/builds/367962040
image

I have opened an issue to this effect: https://github.com/dwyl/aws-sdk-mock/issues/124
If you want to make the change in _your_ PR so that the build passes, please go for it! 
Thanks!

**Comment by chris-armstrong** [comment]
Ok, that seems to work with the latest nodejs (v9)

**Comment by nelsonic** [comment]
@chris-armstrong latest version on NPM `2.0.0` contains the latest Sinon. thanks again. 🥇

**Pull request merged**
