### PR TITLE
Refactored code to use config parameters from the real constructor

### PR DESCRIPTION
**Pull request by jruts**
Solution for  https://github.com/dwyl/aws-sdk-mock/issues/12.

The issue was that the method mocks were created before the actual constructor was called. Therefore the configuration object was lost.

So instead of mocking the methods directly we only register them. When the actual constructor is called we will create the actual method mocks.

Mocks that  are created when the constructor has already been called will be created directly.

### CODE REVIEW

**Comment by nelsonic** [comment]
@jruts this will be version `1.0.7` please update `package.json` on your branch. thanks!

**Comment by boyarskiy** [comment]
@jruts Great solution! :+1:

**Comment by nelsonic** [comment]
@jruts sweet! :lollipop: 
If you have time, please add a usage example to the Readme. thanks! :+1:

**Comment by jruts** [comment]
@nelsonic the Readme has been updated.

**Comment by nelsonic** [comment]
@jruts amaze! :tada: 
Merging.

**Pull request merged**
