### PR TITLE
Add `on` method to request object

### PR DESCRIPTION
**Pull request by abetomo**
Since there was no on method and the following error occurred
```
TypeError: request.on is not a function
```

Reference:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html

If you better open the issue first, I will do so, please point out.

fixies: #135

### CODE REVIEW

**Comment by fujio0000** [comment]
@nelsonic
I am having the same problem.
When is the merge around?

**Comment by danieljin** [comment]
@nelsonic Can we get this merged??

**Comment by Swapniljani08** [comment]
can we please get this merged

**Comment by nelsonic** [comment]
`aws-sdk-mock@3.1.0` now on NPM. 
thanks @abetomo 🥇

**Comment by Swapniljani08** [comment]
Thank you so much @abetomo @nelsonic ! you guys are awesome

**Comment by nelsonic** [comment]
@Swapniljani08 _all_ thanks go to @abetomo for his _concise_ contribution! 🎉

**Comment by Swapniljani08** [comment]
so would it be too far to ask for support of request.send  ?

**Comment by nelsonic** [comment]
@Swapniljani08 please open an issue and create a PR, we're happy to merge. 👍

**Comment by abetomo** [comment]
@nelsonic Thank you!

**Pull request merged**
