### PR TITLE
issue#97 - Stream depending on params for S3.getObject

### PR DESCRIPTION
**Pull request by moish83**

### CODE REVIEW

**Comment by moish83** [comment]
@nelsonic, this PR should resolve the #97 issue.
Who can review?

**Comment by nelsonic** [comment]
Hi @moish83 indeed the code appears to address #97 any chance you can add some test(s) to keep Travis CI happy? 🙏

**Comment by moish83** [comment]
@nelsonic, yes, I'll add tests.
The travis CI failed on something unrelated to the change (some missing module).

**Comment by moish83** [comment]
@nelsonic, added test scenario.
When you approve and merge, will a new version gets published automatically?

**Comment by nelsonic** [comment]
Travis-CI is _mostly_ happy:
https://travis-ci.org/github/dwyl/aws-sdk-mock/builds/774535824
image

Just one of the builds is failing:
https://travis-ci.org/github/dwyl/aws-sdk-mock/jobs/774535825#L235
image

Looks like this is just an issue with Tap running on `node.js v.16.3.0`
Specifically: https://www.npmjs.com/package/jackspeak 🤷‍♂️ 

Think it's safe to merge this, but we may need to disable v16 for now. 💭

**Comment by moish83** [comment]
Sounds good to me

**Review by nelsonic — APPROVED** [review]
@moish83 thanks for this addition/fix + test. 👍

**Comment by nelsonic** [comment]
Merging now. Will tidy up CI on `localhost` then push changes up.

**Comment by nelsonic** [comment]
@moish83 `aws-sdk-mock@5.2.0` on NPM now contains your code. 🚀  (Thanks again!)

**Pull request merged**
