### PR TITLE
remove old (no longer supported) versions of node.js from .travis.yml

### LINKED ISSUE #237: Remove old versions of Node.js from .travis.yml + Update Deps
We have a couple of ancient versions of node.js in the `.travis.yml` file:
https://github.com/dwyl/aws-sdk-mock/blob/f78025fc129af5761fef6dee43d7ded27c8c49fb/.travis.yml#L2-L7

Also, we have "node" which is just the "current" version, i.e. not very explicit. 
It caused a break in a recent PR build: https://github.com/dwyl/aws-sdk-mock/pull/236#issuecomment-860849030

Going to remove the older versions and the non-specific one.

### PR DESCRIPTION
**Pull request by nelsonic**
+ [x] fixes #237

### CODE REVIEW

**Comment by nelsonic** [comment]
Build passes again. Going to attempt to update `dependencies` ... ⏳

**Comment by nelsonic** [comment]
This is as far as I'm going to take updates tonight. `tap` removed the `done()` in `v15` so that will require a bit more work ...
just going to bump the version and publish to NPM.

**Comment by nelsonic** [comment]
@iteles please review & merge when you can. Thanks. 🌻

**Review by iteles — APPROVED** [review]
Perfect, thanks @nelsonic

**Pull request merged**
