### PR TITLE
upgrade packages

### PR DESCRIPTION
**Pull request by abetomo**
* There was a major version upgrade, so I upgraded the package.
* Modify the tests according to the changes in node-tap.

### CODE REVIEW

**Comment by nelsonic** [comment]
Assigning this to myself to merge when I get back to my desktop (which is signed into NPM). Thanks @abetomo 🥇

**Comment by abetomo** [comment]
#238

**Comment by nelsonic** [comment]
@abetomo apologies. I forgot you had done this work. 🤦  (_my bad!_)
Still worth having for the update to `Tap` where you removed the `done` from the tests. 💭

**Comment by abetomo** [comment]
@nelsonic Thank you for your comment.
I've opened a PR with only updated devDependencies.
#239

**Pull request closed without merging**
