### PR TITLE
Replace traverse with neotraverse

### PR DESCRIPTION
**Pull request by wojtekmaj**
This PR replaces traverse with neotraverse, a fork and TypeScript rewrite of traverse with 0 dependencies (as opposed to 66: https://npmgraph.js.org/?q=traverse) and lots of improvements.

### CODE REVIEW

**Review by LuchoTurtle — APPROVED** [review]
Thank you @wojtekmaj for the PR, it is really appreciated!
Was not aware of https://github.com/puruvj/neotraverse, it seems to be a great library from the original `traverse`. 
Since this looks like a simple change and since `neotraverse` is 1-1 compatible with `traverse`, I'm approving these changes.

Tagging @nelsonic to give a quick look over and we'll get it merged ASAP :)

**Comment by PuruVJ** [comment]
Looks awesome! I just checked this lib on npmgraphs, and the entire middle part will be gone after this PR is merged and released 😄

CleanShot 2024-07-17 at 10 52 53

**Review by nelsonic — COMMENTED** [review]
@wojtekmaj thanks for the PR! 🙏 
@LuchoTurtle thanks for tagging. 🏷️ 👌 
I'm all for PRs that _reduce_ our dependency tree! 🎉 

Never heard of `neotraverse` ... 🤷‍♂️ 
Prolly cause it was first published 6 days ago! 💭 

https://www.npmjs.com/package/neotraverse?activeTab=versions 👀 
image

_Currently_ has _very_ low usage: https://www.npmjs.com/package/neotraverse
image

By contrast `traverse` is "community tested": https://www.npmjs.com/package/traverse
image

If we merge this PR we will 200x the `neotraverse` download stats ... 📈 
https://www.npmjs.com/package/aws-sdk-mock
image

Looks reasonably well-documented:  https://github.com/PuruVJ/neotraverse
image
Only two contributors ... https://github.com/PuruVJ/neotraverse/graphs/contributors
image

@PuruVJ seems legit. 
image

@Aslemammad also seems technically competent! 👌 
image


My only "concern" is this: 
New modules appearing to "fix" the problems of older/bloated ones is great!
But it's a [_massive_ attack vector](https://www.cloudflare.com/en-gb/learning/security/glossary/attack-vector/) for getting malicious code onto the computers of key engineers using AWS to deploy their apps! 

Right now the code for `neotraverse` https://github.com/PuruVJ/neotraverse/tree/main/src looks fine! 
But if a _malicious_ person can inject code into it, they could steal AWS keys on dev machines, spin up $$$$$$ of machines on AWS and then erase their tracks ... 

We _definitely_ don't want to be in the news, e.g: 
https://www.trendmicro.com/vinfo/mx/security/news/cybercrime-and-digital-threats/hacker-infects-node-js-package-to-steal-from-bitcoin-wallets

So `while` I appreciate the enthusiasm, I am naturally cautious/paranoid. 💭 

@wojtekmaj how did you find out about this package?

**Comment by PuruVJ** [comment]
> Thank you @wojtekmaj for the PR, it is really appreciated! Was not aware of https://github.com/puruvj/neotraverse, it seems to be a great library from the original `traverse`. Since this looks like a simple change and since `neotraverse` is 1-1 compatible with `traverse`, I'm approving these changes.
> 
> Tagging @nelsonic to give a quick look over and we'll get it merged ASAP :)

I would suggest building this PR. While the API itself is identical, neotraverse doesn't ship with CommonJS, which could break the entire build. we will have to switch `neotraverse/legacy` in that case

**Comment by wojtekmaj** [comment]
Hi! Thanks @nelsonic for a detailed write-up.

I found the package through author's Twitter: https://x.com/puruvjdev

While I definitely hear your concerns, I'm wondering, how did you manage to keep up with `traverse` updates, and perhaps more importantly, _all 66 of its dependencies_ updates, until this point? Out of these 66 dependencies, 58 (!) have one maintainer. 

That setup is infinitely easier to sneak shady stuff into. 

One of the reason is that you will NEVER be able to lock a version for secondary dependencies - you can only do that for _your own_ dependencies. With `neotraverse`, assuming (unrightfully so, in my opinion) zero trust in the maintainer, one can review the entire source code, and simply lock its version to `0.6.11`, completely removing attack vector, thanks to `neotraverse` having zero dependencies.

**Comment by PuruVJ** [comment]
The test is breaking due to neotraverse being ESM-only. @wojtekmaj could you switch it to neotraverse/legacy?

**Comment by nelsonic** [comment]
@wojtekmaj to answer your question:

> _how did you manage to keep up with traverse updates, and perhaps more importantly, all 66 of its dependencies updates, until this point?_
 
We didn't even _`try`_ to keep track of the dependencies in `traverse` 
it's _assumed_ to be "stable" and reliable as it's maintained/published by [**`@ljharb`**](https://github.com/ljharb). 🦸‍♂️ 
We rely - perhaps naively - on Snyk https://snyk.io/test/github/dwyl/aws-sdk-mock to monitor the deps tree. 

However we've _recently_ had a "[`false` negative](https://en.wikipedia.org/wiki/False_positives_and_false_negatives)" from Snyk - in a private client project, not this one - so our attention has been drawn to security concerns ... 💭 The `false` negative from Snyk and unmanageable dependency trees  in `Node` has actually caused our client CTO to totally re-evaluate their use of `Node.js` 🤯 and they've decided to migrate their systems to [`Go`](https://github.com/dwyl/learn-go/issues/5#issuecomment-2212051570)! 😬 

Would definitely have preferred to see an _attempt_ to improve `traverse` before creating a brand new module. 
i.e. open an issue proposing to remove the dependencies from `traverse` before forking/re-writing it ... 
Totally _understand_ that sometimes it's [_faster_](https://github.com/dshaw/env/pull/8) to rewrite something than to deal with politics ... ⏳ 
But it also leads to fragmentation in the ecosystem and `JavaScript` fatigue ... 🙃 

Anyway ... 💭 

Let's get this PR updated to use `neotraverse/legacy`. 🙏

**Comment by PuruVJ** [comment]
> Would definitely have preferred to see an attempt to improve traverse before creating a brand new module.
i.e. open an issue proposing to remove the dependencies from traverse before forking/re-writing it ...
Totally understand that sometimes it's https://github.com/dshaw/env/pull/8 to rewrite something than to deal with politics ... ⏳
But it also leads to fragmentation in the ecosystem and JavaScript fatigue ... 🙃

That's a giant discussion we should not have here 😅 Just know that traverse was all good before it was "sabotaged" and based on the discussion, it seems unlikely its gonna get any lighter

Anyways, thanks a lot for agreeing! Let's get this done! 🚀

**Comment by wojtekmaj** [comment]
Sorry folks for the delay! I literally became a father since my last comment 🤣 Fixed the import to `/legacy`.

**Comment by LuchoTurtle** [comment]
Approving the workflow. All tests pass ❤️ 

@wojtekmaj oh wow! Huge congratulations! You shouldn't be worried about this PR now, go enjoy the perks of fatherhood! :D

**Comment by PuruVJ** [comment]
Whoaaa Huge congrats @wojtekmaj!! 🔥🎉🎉🎉

**Comment by LuchoTurtle** [comment]
Now THAT is a cute one! 👶  We gotta work on creating him a `GitHub` account ASAP, fella oughta learn the ways young! 😛 (literally 5 hours after being born, that has to be some sort of record on this site xD)

**Comment by PuruVJ** [comment]
Imagine Github signup doesn't allow today's date 🥲 Someone make a petition

**Comment by nelsonic** [comment]
Register your kid's account with a birthday 20 years ago and in a few years time he can update it. 😉 
Both our kids have `GitHub` accounts and they aren't allowed _near_ a computer yet. ⌨️ 🚫 
I sometimes mention them in a comment/commit giving them easter-eggs to find in the future. 🥚 ⏳

**Comment by PuruVJ** [comment]
@nelsonic i believe we're waiting for your approval 👀👀

**Comment by nelsonic** [comment]
@PuruVJ thanks for drawing our attention to the bloat https://x.com/passle_/status/1810805530706792930 ... 🤦‍♂️ 
Lame ... 😕 
image

I'm all for modularity and re-use. but c'mon ... 🤷‍♂️ 
this spaghetti is _clearly_ a dependency/package download count inflation exercise 📈 
to get to the top of some [leaderboard](https://gist.github.com/anvaka/8e8fa57c7ee1350e3491). 🙄 https://x.com/passle_/status/1810939058324938851
66 child dependencies instead of zero is _totally_ the wrong direction for maintainability!
https://www.npmjs.com/~ljharb is definitely "winning" on package _quantity_ ... 
image

Anyway ... 🙊 
Thanks again for drawing our attention to it. 🔍

**Review by nelsonic — APPROVED** [review]
# :shipit:

Thanks again for the PR @wojtekmaj and congrats! 👶 ❤️ 
@PuruVJ good work on keeping `neotraverse` low dependency. 🥇 
Forking is _part_ of Open Source. 👌 
@LuchoTurtle over to you to create the new release and publish to NPM.  📦 
Given that `neotraverse` is a drop-in-replacement with no (test) breaking changes, it prob doesn't need a _major_ version just a _minor_; e.g: `6.0.4` -> `6.1.0`? but up to you. 💭

**Comment by wojtekmaj** [comment]
Sorry for spamming you the last time, but I just gotta say, this discussion was just THE NICEST. It belongs to an Open Source Museum once someone establishes one.

**Comment by PuruVJ** [comment]
Thank you all!! Excited to see gigabytes drop across entire internet thanks to this change 😄

**Pull request merged**
