### PR TITLE
Add support for mocking AWS SDK's promises

### PR DESCRIPTION
**Pull request by jcready**
As of March 31, 2016 [the AWS SDK now supports Promises](https://blogs.aws.amazon.com/javascript/post/Tx3BZ2DC4XARUGG/Support-for-Promises-in-the-SDK). This means that you can now do things like this:

```js
var s3 = new AWS.S3({apiVersion: '2006-03-01', region: 'us-west-2'});
var params = {
  Bucket: 'bucket',
  Key: 'example2.txt',
  Body: 'Uploaded text using the promise-based method!'
};
var putObjectPromise = s3.putObject(params).promise();
putObjectPromise.then(function(data) {
  console.log('Success');
}).catch(function(err) {
  console.log(err);
});
```

Attempting to use aws-sdk-mock to mock methods that now no longer require a callback function causes issues, most notably: `TypeError: callback is not a function`. This PR attempts to resolve this issue by checking to see if the mocked method was passed a callback function. If it was passed a callback function then everything should behave exactly as it did before. But if it wasn't then it returns an object containing a single method `promise` which, when invoked, will execute the user's mocked response and the promise will branch based on what the callback returns. It will utilize the native/global promise if available, but it will also pick up on calls to `AWS.config.setPromisesDependency` so that the mocks can create new promises with the provided promise constructor.

### CODE REVIEW

**Comment by nelsonic** [comment]
@jcready thanks for the PR! would you mind adding some tests & docs (in the readme) for this addition?

**Comment by jcready** [comment]
@nelsonic to properly test this I would either need to depend on a native Promise implementation (which Node 0.10.36 doesn't have AFAIK) or I would have to include a polyfill for it. What's your preference?

**Comment by nelsonic** [comment]
Good question. I think we should probably migrate to using `4.3.2` as the baseline node.js version for this module... 
@nikhilaravi thoughts?

**Comment by jcready** [comment]
I've added tests for environments that support Promises natively. I'm explicitly telling Istanbul to ignore one line because it would require that you test against an older version of the aws-sdk, which that line is specifically trying to handle.

**Comment by nikhilaravi** [comment]
@jcready @nelsonic I think upgrading to node 4.3.2 should be fine! There's no reason not to now Lambda supports it.

**Comment by nikhilaravi** [comment]
@nelsonic @jruts has this PR had a final review?

**Comment by jruts** [comment]
@nikhilaravi looks fine to me

**Comment by nelsonic** [comment]
@nikhilaravi yeah, looks good.
@jcready would you mind increasing the version number in `package.json` to `1.3.0` 
or ... https://github.com/dwyl/aws-sdk-mock/issues/32 ?

**Comment by jcready** [comment]
@nelsonic done.

**Comment by nikhilaravi** [comment]
@jcready ah looks like there are some conflicts - would you be able to resolve them?

**Comment by nelsonic** [comment]
@jcready thanks for updating the version, please let us know when merge conflicts are resolved so we can merge and `npm publish`! 👍

**Comment by jcready** [comment]
@nikhilaravi @nelsonic I've resolve the merge conflict (literally just the package.json version).

**Comment by nelsonic** [comment]
@jcready let's ship it! :shipit:

**Comment by nelsonic** [comment]
@jcready your new version is on NPM: `aws-sdk-mock@1.3.0` 🚀 
thanks again for the contribution! welcome to @dwyl! 👍

**Pull request merged**
