### PR TITLE
fix: unhandled promise rejections when using callbacks

### PR DESCRIPTION
**Pull request by bchociej**
Issue #53

### CODE REVIEW

**Comment by nelsonic** [comment]
Hi @ronanyeah! (_What's the Crack_? 😜 )
Hope life is treating you well at your [new job](https://www.linkedin.com/in/ronanemccabe) and you're learning _loads_ from working with @pgte & Co! ❤️ 

_Given_ that you are the **_foremost_ authority** on **`Promises`** in the @dwyl community, 
and you _also_ happen to know _way_ more about AWS than me, would you mind taking a look at this PR and confirming it's good to ship? :shipit: ❓ 

> **Note**: I've read the code and it "**LGTM**", but as you _know_ I'm not a ["Promises"](https://youtu.be/llDikI2hTtk) person... so any help would be _much_ appreciated! 👍

**Comment by nelsonic** [comment]
I've since been informed that https://en.wikipedia.org/wiki/Craic is the correct spelling! 
(_thanks @ronanyeah ..._ 😜 )

**Comment by jackcarlisle** [comment]
hey @bchociej, please resolve merge conflicts and then assign to me when ready

**Comment by bchociej** [comment]
@jackcarlisle conflicts resolved; not sure how to assign (or if I even can)

**Comment by nelsonic** [comment]
Guys we've added functionality without documentation (_usage examples in the readme_) ....

**Comment by jackcarlisle** [comment]
@nelsonic I thought that the changes were internal meaning that the external API remains the same?

**Comment by bchociej** [comment]
@jackcarlisle @nelsonic from my POV, this PR brings the code in line with expected behavior, but of course that's only this one person's opinion!

**Comment by nelsonic** [comment]
@bchociej yeah, I _agree_ that promise rejections is an "_expected behaviour_" but it's not one that we have documented. i.e: we aren't _showing_ people how to use this functionality. 🤔

**Pull request merged**
