### PR TITLE
Add minimal createReadStream support

### PR DESCRIPTION
**Pull request by motiz88**
This is my implementation of #39. I tried to somewhat harmonize the callback, Promise and stream code paths, while keeping all the previously supported use cases.

### CODE REVIEW

**Comment by nelsonic** [comment]
@motiz88 this is a _great_ addition! would you mind adding another test to ensure that we are still getting coverage? (_codecov is reporting that we've added 6 lines which are not being covered..._)

**Comment by motiz88** [comment]
Well! The Node 0.10 thing sure caught me off guard. Better now? :smile:

**Comment by nelsonic** [comment]
Golden! Much better! Thanks!

**Comment by nelsonic** [comment]
@motiz88 new version `v1.5.0` published. 👍

**Pull request merged**
