### PR TITLE
Add createReadStream payload support

### PR DESCRIPTION
**Pull request by MrHen**
I have a scenario where I need to test S3 streams. This feature would save me a lot of trouble.

### CODE REVIEW

**Comment by MrHen** [comment]
@nelsonic not sure what the normal PR procedure is for this repo. Anything in particular I need to do?

**Comment by bdruth** [comment]
👍 Would like to see this as well.

**Comment by jonathannaguin** [comment]
When can we expect this to be merged?

**Comment by rmatec** [comment]
This is a very useful feature. Could we have it merged please?

**Comment by nelsonic** [comment]
@MrHen thanks _very_ much for adding this feature. (_really sorry to keep you waiting for the PR..._)
We _usually_ require an update to the Readme to inform _others_ that the feature is available.
But it seems a reasonably "_expected_" feature to have so happy to merge. thanks!

**Comment by nelsonic** [comment]
@MrHen new version on NPM: `aws-sdk-mock@1.6.0` contains your changes. 👍  (_thanks again!_)

**Comment by MrHen** [comment]
@nelsonic Thanks! Sorry for pestering so much. :)

**Comment by nelsonic** [comment]
@MrHen not at all. you did a _superb_ job of adding the functionality _with **tests**_! ❤️  (_thanks_!)

**Pull request merged**
