### PR TITLE
Inject client configs into params to be validated by ParamValidator.

### PR DESCRIPTION
**Pull request by RicardoMiguel**

### CODE REVIEW

**Comment by jackcarlisle** [comment]
Hi @RicardoMiguel, would you mind adding a description to this PR including a link to an issue that has been opened regarding the changes made in this PR? If it doesn't exist please create one so that a discussion can be opened on the topic and that the need for these changes is validated. If you haven't already, please see our [contribution guidelines](https://github.com/dwyl/contributing/blob/master/README.md) for making PRs to [dwyl](https://github.com/dwyl)

**Comment by nelsonic** [comment]
looks like we need to add some tests too ... 🙄 (_to keep Codecov happy_)

**Comment by RicardoMiguel** [comment]
@nelsonic I've sorted it out. You can merge it now.

**Comment by nelsonic** [comment]
@RicardoMiguel if you have time to fix the merge conflicts, please do and re-open this PR. 👍

**Pull request closed without merging**
