### PR TITLE
You can now mock out multiple methods on the same service

### PR DESCRIPTION
**Pull request by jruts**
https://github.com/dwyl/aws-sdk-mock/issues/11

### CODE REVIEW

**Comment by nelsonic** [comment]
@jruts on open source projects we try to always tie a PR to an issue where the problem/proposal is discussed *before* it is implemented. this makes it easier for other people in the community to follow *why* the module has changed... 
In *this* case we *discussed* the issue you are solving *verbally* but its worth *updating* the PR description to add some detail on why you are submitting this PR. :+1:

**Comment by nelsonic** [comment]
Nice one. code is clear. good tests and 100% coverage maintained. merging. :+1:

**Comment by nikhilaravi** [comment]
@jruts  Good job spotting the error :bug: !

**Comment by nelsonic** [comment]
@jruts I've just added you to the `npm` for `aws-sdk-mock` so you can publish this latest version. 
(*let me know if you need a quick refresher.*)

**Pull request merged**
